### PR TITLE
small pp console fix....

### PR DESCRIPTION
**Pull request by Sorte1**
just better.... also doesn't do a shit ton of warnings...

### CODE REVIEW

**Comment by Mixaz017** [comment]
What does this fix

**Comment by Mixaz017** [comment]
nvm

**Comment by Sorte1** [comment]
just makes so that console never gets disabled

**Comment by Mixaz017** [comment]
I was too lazy to actually test it myself LOL

**Comment by NullDev** [comment]
> I was too lazy to actually test it myself LOL

@Mixaz017 "nULL, pLEaSe TeST YoUr cOde bEforE pUShiNG"

**Comment by Mixaz017** [comment]
@NullDev I did test before merging, unlike someone else here🤔

**Pull request merged**
