### PR TITLE
Menutimer CSS fix

### PR DESCRIPTION
**Pull request by Zykkl**
Fixed Menutimer CSS so gamemode and time don't stay on top of eachother

### CODE REVIEW

**Comment by Mixaz017** [comment]
I think this pr is meant for v9 branch
Will review tomorrow

**Comment by Mixaz017** [comment]
Wait isn't this incomplete lol

**Comment by Zykkl** [comment]
guess who fucked up, NANANANANANANA xD

**Comment by Zykkl** [comment]
it's my first pr shut

**Comment by Mixaz017** [comment]
XDDDD

**Pull request closed without merging**
